1.Introduction - task for the first lesson of the course.
Yulson/ruby-automation pull request #4
Opened 2017-03-01 21:53 UTC by Yulson

Prepared tests for demo.redmine.org using TestUnit and Selenium Webdriver.

2017-03-18 14:44 UTC, Yulson commented
@d-konovalov please review

2017-03-20 16:03 UTC, d-konovalov requested changes

2017-03-20 16:03 UTC, d-konovalov commented on Issue.rb
> +		@issue_name = Faker::Team.name
fix to @name instead of @issue_name

2017-03-20 16:03 UTC, d-konovalov commented on Issue.rb
> +	def initialize(options={})
```ruby
def initialize(type)
  @name = Faker::Team.name
  @type = type
end
```

2017-03-20 16:03 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +	    actual_array_subjects = Array.new
var = []

2017-03-20 16:03 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +	    @driver.find_elements(:css, '.subject').each {|element| actual_array_subjects.push(element.text)}
my_subjects = @driver.find_elements(:css,....).map {|el| el.text}

2017-03-20 16:03 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +	    assert_match(/#{expected_subject}/, actual_array_subjects.to_s)
assert_true(my_subjects.include? expected_subject)

2017-03-29 21:15 UTC, Yulson commented
Hi @d-konovalov,
I did all changes according to your comments in main project. Could you please review it again.

2017-03-30 15:33 UTC, d-konovalov requested changes

2017-03-30 15:33 UTC, d-konovalov commented on 4. Operators-and-onstructors/Operators-and-constructors-task1.rb
> +#1. Create method which gets 10 random integers (from 0 to 9) (generate it using while or until)
first of all we should have a method as task says
and second: try to reduce lines number as much as possible

2017-03-30 15:33 UTC, d-konovalov commented on Main_project_Helpers.rb
> + 		@driver.find_element(:css, '.odd [value="5"]:nth-child(1)').click
hardcoded values in locator is a bad sign
if you don't have now ideas how to fix it please ask me for help

2017-03-30 17:49 UTC, merged