Updated Main-project_tests with new tests according to Lesson 4_Opera…
Yulson/ruby-automation pull request #8
Opened 2017-04-16 09:53 UTC by Yulson

@d-konovalov, in this commit I've completed Task2 from Lesson 4 (Operators and Constructions).
2. add to your solution next test:
- create project
- make a random action: create or not a new bug issue
- open project page,
- open issues tab
- if there is a bug present then add self to watchers
- if no then create a new bug issue and then add self to watchers
- Verify that there is a bug issue and that current user is a watcher

2017-04-17 07:27 UTC, d-konovalov requested changes

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Helpers.rb
> +		if @driver.find_element(:css, '.nodata').displayed?
```if``` and ```rescue``` statements can be replaced with:



```ruby
@driver.find_elements(:css,'.nodata').empty?
```

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Helpers.rb
> +			open_issues_tab(project)
if you have this line in both ```if``` and ```else``` blocks please place it after ```if``` statement
you won't need ```else``` block at all then

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Helpers.rb
>  	def register_user(user_data)
if you use this as an argument:



```
user_data=nil
```

you won't need to call this method like this:


```
register_user({})
```

just


```
register_user
```
and that's it

(this is a mistake)

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +	  	actual_login = @driver.find_element(:css, '[class="user active"]').text
this is not the best css locator
if this ```'.user'``` or this ```'.active'``` doesn't work you can use this one ```'.user.active'```

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +	    issue = create_new_issue({type: '1'})
please remove curly braces, we don't need them here

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +	    actual_array_subjects = @driver.find_elements(:css, '.subject').map {|element| element.text}
this ```map``` statement also can be simplified if you use 'syntax sugar' like this


```ruby
map(&:text)
```

and btw
when you trying to find name for variable in cases like this (when its 'life' period is very short) please use shorter names. ```el``` would be enough

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +	    issue1 = create_new_issue({type: '1'})
remove curly braces

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +     	actual_array_subjects = []
this line is redundant

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +		if is_issues_tab_empty?(project) == true
```== true``` is redundant

2017-04-17 07:27 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +			add_self_to_watchers(project, issue)
this line should be extracted from both ```if``` and ```else``` code blocks
and placed after ```if``` statement

2017-04-17 07:27 UTC, d-konovalov commented on Project.rb
> +		project_url = String.new
redundant

2017-04-17 07:27 UTC, d-konovalov commented on Project.rb
> +		project_url = "http://demo.redmine.org/projects/#{directory}"
we don't need this one here```project_url =``` since we create local var we don't use anymore

2017-04-17 07:45 UTC, Yulson commented on Project.rb
> +		project_url = "http://demo.redmine.org/projects/#{directory}"
@d-konovalov,  thank you a lot for a quick respond. Im proceeding with rework.

2017-04-25 16:35 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +    		retry unless (tries -=1).redo
I suppose ```redo``` is a kind of mistake?

2017-05-03 19:35 UTC, Yulson commented
@d-konovalov, could you please review this pull request and finally merge it to master.
With this pull-request the following tasks should be finally done:
1) Task for Lesson 5 _"Object, Class, Method, Variables"_ (Simple Trello model with simple Unit tests)
2) Task with raising and rescuing an Exception for Lesson 7.
3) Changes in Main_project_Tests_TestUnit.rb and Main_project_Helpers.rb: changing locators, removing odd variables and methods.

2017-05-04 14:35 UTC, d-konovalov commented on Main_project_Helpers.rb
>  		project = project_data.empty? ? Project.new : Project.new(project_data)
you should choose which line to delete this or previous one
both of them assign a value to 'project' variable

2017-05-04 15:03 UTC, Yulson commented on Main_project_Helpers.rb
>  		project = project_data.empty? ? Project.new : Project.new(project_data)
@d-konovalov, I left second line. Hovewer it's longer but for me it's more clear. I also did the same changes for user and issue.

2017-05-10 12:04 UTC, d-konovalov requested changes

2017-05-10 12:04 UTC, d-konovalov commented on Main_project_Tests_TestUnit.rb
> +    		@driver.find_element(:css, '.overview.selected').displayed?
define method which will raise an Exception in specific case
then you'll be able to rescue it

2017-05-10 12:17 UTC, merged